services:
  cloudbeaver:
    image: dbeaver/cloudbeaver
    container_name: cloudbeaver
    restart: always
    ports:
      - "8978:8978"
    volumes:
      - cloudbeaver-data:/opt/cloudbeaver/workspace
    networks:
      - PrviNetwork

volumes:
  cloudbeaver-data:

networks:
  PrviNetwork:
    external: true

