services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mauFJcuf5dhRMQrjj 
      MYSQL_DATABASE: classmanagement
      MYSQL_USER: user
      MYSQL_PASSWORD: mauFJcuf5dhRMQrjj
    networks:
      - PrviNetwork

volumes:
  mysql-data:

networks:
  PrviNetwork:
    external: true
