kind: role
version: v7
metadata:
  name: administrator
spec:
  allow:
    logins: ["root"]
    node_labels:
      "*": "*"
    kubernetes_groups: ["system:masters"]
    rules:
      - resources: ["*"]
        verbs: ["*"]
  deny: {}